-- =============================================================================
-- Migration: Drop 13 orphan public-schema functions
-- Date: 2026-05-08 (originally 14; reduced to 13 after deploy.yml caught
--       a 3rd reference path — RLS policies — that the inventory missed)
-- Phase: 9.2 (Prod-vs-migration drift reconciliation)
--
-- WHY:
-- Phase 9.1 inventory (`docs/security-audit/phase-9-drift-inventory.md`,
-- generated by `scripts/database/inventory-drift.ts`) identified 14 functions
-- in the public schema with zero application code references AND zero
-- pg_trigger.tgfoid references. The first deploy of this migration FAILED
-- because `get_user_space_ids(uuid)` has a third reference path the inventory
-- missed: it's used by 10 RLS policies (qual / with_check) across
-- point_transactions, reward_points, reward_redemptions, and space_members.
-- Confirmed by `scripts/database/check-fn-policy-refs.ts`. The other 13
-- candidates have zero policy refs and are safe to drop.
--
-- These functions are ACCUMULATED DRIFT from earlier app evolution:
--   • Trial helpers (3): superseded by app-side Polar status checks
--   • Admin helpers (2): never wired up
--   • Space helpers (3): get_personal_space_id, is_personal_space (no refs);
--                         get_user_space_ids RETAINED — RLS-policy-bound
--   • Cron-style cleanup (3): no scheduler ever wired them up
--   • Stats RPCs (3): never called from app code, no triggers, no policies
--
-- IDEMPOTENT:
--   Each DROP uses IF EXISTS + the full signature (uuid, integer, text) so
--   the migration is safe on fresh CI replay (functions don't exist there
--   yet) and safe to re-run on prod (post-drop, the IF EXISTS no-ops).
--
-- REVERSIBILITY:
--   The function bodies are preserved in earlier migration files. If any of
--   these turns out to be needed, restore via CREATE OR REPLACE FUNCTION
--   from the source migration. Search supabase/migrations/ by function name
--   to find the source.
--
-- VERIFY POST-DEPLOY:
--   Re-run `npx tsx scripts/database/inventory-drift.ts` — expect 0 true
--   orphans (the trigger-callback false-positives stay the same: 11).
-- =============================================================================

-- Trial helpers — superseded by app-side Polar status checks (lib/services/polar/*)
DROP FUNCTION IF EXISTS public.get_trial_days_remaining(uuid);
DROP FUNCTION IF EXISTS public.is_user_in_trial(uuid);
DROP FUNCTION IF EXISTS public.record_trial_started(uuid);

-- Admin helpers — never wired up (admin-session uses app-side role checks)
DROP FUNCTION IF EXISTS public.get_admin_level();
DROP FUNCTION IF EXISTS public.has_admin_permission(text);

-- Space helpers — app uses is_personal=true flag + space_members joins instead
DROP FUNCTION IF EXISTS public.get_personal_space_id(uuid);
-- get_user_space_ids(uuid) RETAINED — used by 10 RLS policies (qual/with_check)
-- across point_transactions, reward_points, reward_redemptions, space_members.
-- Dropping it would require dropping + recreating those policies, which is
-- a meaningfully different change and out of scope for this migration.
-- Tracked as a follow-up: re-evaluate whether the policies should inline
-- the underlying space_members lookup directly (eliminating the function).
DROP FUNCTION IF EXISTS public.is_personal_space(uuid);

-- Cron-style cleanup — no Vercel cron wiring exists for these (vercel.json crons
-- list is unrelated). If reinstated, they'd need an entry in vercel.json crons.
DROP FUNCTION IF EXISTS public.cleanup_expired_magic_tokens();
DROP FUNCTION IF EXISTS public.cleanup_expired_reset_tokens();
DROP FUNCTION IF EXISTS public.cleanup_old_monetization_logs();

-- Stats / activity RPCs — never called. Activity feed reads activity_logs
-- directly; goal stats are computed app-side.
DROP FUNCTION IF EXISTS public.get_goal_check_in_stats(uuid);
DROP FUNCTION IF EXISTS public.get_monetization_error_summary();
DROP FUNCTION IF EXISTS public.get_unified_activity_feed(uuid, integer);

DO $$
BEGIN
  RAISE NOTICE '✅ Phase 9.2: dropped 13 orphan public-schema functions';
END
$$;
