-- ============================================================================
-- Drop PostGIS Extension
-- ============================================================================
-- The PostGIS extension was installed defensively in
-- 20260125000001_create_location_tracking.sql ("Enable PostGIS extension for
-- geographic calculations") but never actually used — the location tables
-- stored raw DECIMAL(10,8) lat/lon, not PostGIS geometry/geography types.
--
-- After removing family location tracking entirely (see migration
-- 20260426000001_drop_location_tracking.sql and CLAUDE.md "Feature Removal
-- Log"), PostGIS has zero references in the database or codebase. Dropping
-- it eliminates:
--   • the spatial_ref_sys system table (which had unfixable security advisor
--     findings — anon/authenticated had INSERT/UPDATE/DELETE/TRUNCATE
--     privileges that could not be revoked from a regular migration role)
--   • 200+ unused PostGIS functions polluting the public schema namespace
--   • PostGIS triggers and supporting metadata
--
-- CASCADE is used because supabase_admin is the only role that can REVOKE
-- the PostGIS-installed grants, and a regular DROP EXTENSION may reference
-- objects we don't fully control.
-- ============================================================================

DROP EXTENSION IF EXISTS postgis CASCADE;
