-- =============================================================================
-- Migration: Phase 9.3 — snap migrations source-of-truth to prod state
-- Date: 2026-05-08
--
-- WHY:
-- Phase 9.1.5 inventory (`docs/security-audit/phase-9-1-5-extended-drift.md`)
-- identified two drift classes that gated the migration squash retry:
--
--   • 24 LOCAL_ONLY functions: defined in earlier migration files but
--     ABSENT from prod (verified via pg_proc lookup 2026-05-08). These
--     are retired-feature callbacks (expense-splitting prep, auto-archive,
--     goal check-in pipeline, voice transcription helpers, recurring goal
--     instance generation, calendar sync verifiers, chore calendar sync).
--     None have any active app code reference. Prod rolled them back at
--     some point; migration source-of-truth never caught up.
--
--   • 25 MISMATCH functions: present in both prod + migrations but with
--     different bodies. Each MISMATCH represents prod-side bug fixes,
--     security hardening, or behavior tweaks that were applied via
--     dashboard / one-off script and never round-tripped back to source
--     control. Examples: assign_task_sort_order added a lock_key for
--     concurrency safety; calculate_expense_splits switched from a
--     two-user model to a partnership/space-members model;
--     get_user_subscription_tier added trial_ends_at handling;
--     handle_new_user_workspace_provisioning added pending-invite logic.
--
-- APPROACH (Phase 9.3 path B — mechanical snap-to-prod):
-- This migration is auto-generated by scripts/database/snap-to-prod-generator.ts.
-- For each MISMATCH function, it emits the exact CREATE OR REPLACE FUNCTION
-- block that pg_get_functiondef returns from prod. For each LOCAL_ONLY
-- function, it emits DROP FUNCTION IF EXISTS ... CASCADE.
--
-- IDEMPOTENCY:
--   • On prod: every CREATE OR REPLACE no-ops (bodies already match);
--     every DROP IF EXISTS no-ops (functions already absent).
--   • On fresh CI replay: earlier migrations CREATE the LOCAL_ONLY funcs,
--     this migration DROPs them; earlier MISMATCH bodies get replaced
--     with prod's body. Net result: CI schema matches prod schema.
--
-- POST-DEPLOY VERIFICATION:
-- Re-run `npx tsx scripts/database/inventory-drift-extended.ts`. Expected:
-- "MISMATCH: 0, LOCAL_ONLY: 0" (down from 19 + 29 documented in
-- the Phase 9.1.5 report).
--
-- TRADE-OFFS (path B vs path C):
-- Path B accepts prod as source of truth without per-function review.
-- A path-C review would have asked, for each MISMATCH, "is prod's body
-- what we INTENDED?" — but the body diffs (assign_task_sort_order
-- lock_key, partnership-aware splits, etc.) are clearly bug fixes the
-- team made in prod and never round-tripped. Treating them as the
-- desired state is the practical call. If any one turns out to be a
-- regression, it can be reverted in a follow-up CREATE OR REPLACE.
--
-- WHY CASCADE on the DROPs: if any historical migration also created
-- a trigger that referenced one of the LOCAL_ONLY functions, the
-- CASCADE silently drops the trigger too — matching prod's internally-
-- consistent state where neither the function NOR a referencing trigger
-- exists.
-- =============================================================================

-- AUTO-GENERATED by scripts/database/snap-to-prod-generator.ts (Phase 9.3 path B)
-- Generated: 2026-05-08T22:36:18.050Z
-- DO NOT edit manually; re-run the generator to refresh.

-- MISMATCH: assign_task_sort_order
CREATE OR REPLACE FUNCTION public.assign_task_sort_order()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE
  max_order INTEGER;
  lock_key BIGINT;
BEGIN
  IF NEW.sort_order = 0 OR NEW.sort_order IS NULL THEN
    -- SECURITY (RT-015): Use advisory lock to serialize sort_order per space.
    -- hashtext() converts space_id UUID to a stable integer for the lock key.
    lock_key := hashtext(NEW.space_id::text);
    PERFORM pg_advisory_xact_lock(lock_key);

    SELECT COALESCE(MAX(sort_order), 0) + 1
    INTO max_order
    FROM public.tasks
    WHERE space_id = NEW.space_id;

    NEW.sort_order = max_order;
  END IF;

  RETURN NEW;
END;
$function$
;

-- MISMATCH: log_reminder_change
CREATE OR REPLACE FUNCTION public.log_reminder_change()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
     DECLARE
       action_type TEXT;
       change_metadata JSONB := '{}'::JSONB;
     BEGIN
       -- Skip DELETE operations entirely to prevent race conditions
       IF TG_OP = 'DELETE' THEN
         RETURN OLD;
       END IF;

       -- Handle INSERT operations
       IF TG_OP = 'INSERT' THEN
         action_type := 'created';
         change_metadata := jsonb_build_object(
           'title', NEW.title,
           'category', NEW.category,
           'priority', NEW.priority
         );

       -- Handle UPDATE operations
       ELSIF TG_OP = 'UPDATE' THEN
         IF OLD.status != NEW.status THEN
           IF NEW.status = 'completed' THEN
             action_type := 'completed';
           ELSIF NEW.status = 'snoozed' THEN
             action_type := 'snoozed';
             change_metadata := jsonb_build_object('snooze_until', NEW.snooze_until);
           ELSIF OLD.status = 'snoozed' AND NEW.status = 'active' THEN
             action_type := 'unsnoozed';
           ELSIF OLD.status = 'completed' AND NEW.status = 'active' THEN
             action_type := 'uncompleted';
           ELSE
             action_type := 'status_changed';
             change_metadata := jsonb_build_object(
               'old_status', OLD.status,
               'new_status', NEW.status
             );
           END IF;
         ELSE
           action_type := 'updated';
         END IF;
       END IF;

       -- Insert activity log (only for INSERT and UPDATE)
       INSERT INTO reminder_activities (reminder_id, user_id, action, metadata)
       VALUES (NEW.id, auth.uid(), action_type, change_metadata);

       RETURN NEW;
     END;
     $function$
;

-- MISMATCH: should_send_notification
CREATE OR REPLACE FUNCTION public.should_send_notification(p_user_id uuid, p_space_id uuid, p_notification_type text, p_channel text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  DECLARE
    v_prefs user_notification_preferences;
    v_current_time TIME;
  BEGIN
    -- Get user preferences (simplified to avoid recursion)
    SELECT * INTO v_prefs
    FROM user_notification_preferences
    WHERE user_id = p_user_id AND (space_id = p_space_id OR space_id IS NULL)
    ORDER BY space_id NULLS LAST
    LIMIT 1;

    -- If no preferences found, use defaults (allow)
    IF v_prefs IS NULL THEN
      RETURN TRUE;
    END IF;

    -- Check if channel is enabled
    IF p_channel = 'email' AND NOT v_prefs.email_enabled THEN
      RETURN FALSE;
    END IF;

    IF p_channel = 'in_app' AND NOT v_prefs.in_app_enabled THEN
      RETURN FALSE;
    END IF;

    -- Check quiet hours
    IF v_prefs.quiet_hours_enabled AND v_prefs.quiet_hours_start IS NOT NULL AND v_prefs.quiet_hours_end IS NOT NULL THEN
      v_current_time := CURRENT_TIME;

      -- Handle quiet hours that span midnight
      IF v_prefs.quiet_hours_start > v_prefs.quiet_hours_end THEN
        IF v_current_time >= v_prefs.quiet_hours_start OR v_current_time < v_prefs.quiet_hours_end THEN
          RETURN FALSE;
        END IF;
      ELSE
        IF v_current_time >= v_prefs.quiet_hours_start AND v_current_time < v_prefs.quiet_hours_end THEN
          RETURN FALSE;
        END IF;
      END IF;
    END IF;

    -- Check type-specific preferences
    IF p_channel = 'email' THEN
      IF p_notification_type IN ('due', 'overdue') AND NOT v_prefs.email_due_reminders THEN
        RETURN FALSE;
      END IF;
      IF p_notification_type IN ('assigned', 'unassigned') AND NOT v_prefs.email_assignments THEN
        RETURN FALSE;
      END IF;
      IF p_notification_type = 'mentioned' AND NOT v_prefs.email_mentions THEN
        RETURN FALSE;
      END IF;
      IF p_notification_type = 'commented' AND NOT v_prefs.email_comments THEN
        RETURN FALSE;
      END IF;
    END IF;

    IF p_channel = 'in_app' THEN
      IF p_notification_type IN ('due', 'overdue') AND NOT v_prefs.in_app_due_reminders THEN
        RETURN FALSE;
      END IF;
      IF p_notification_type IN ('assigned', 'unassigned') AND NOT v_prefs.in_app_assignments THEN
        RETURN FALSE;
      END IF;
      IF p_notification_type = 'mentioned' AND NOT v_prefs.in_app_mentions THEN
        RETURN FALSE;
      END IF;
      IF p_notification_type = 'commented' AND NOT v_prefs.in_app_comments THEN
        RETURN FALSE;
      END IF;
    END IF;

    RETURN TRUE;
  END;
  $function$
;

-- MISMATCH: increment_template_usage
CREATE OR REPLACE FUNCTION public.increment_template_usage()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  -- Find which template was used (if any) and increment its usage count
  -- This will be called when a goal is created with a template_id
  IF NEW.template_id IS NOT NULL THEN
    UPDATE goal_templates
    SET usage_count = usage_count + 1
    WHERE id = NEW.template_id;
  END IF;
  RETURN NEW;
END;
$function$
;

-- MISMATCH: increment_template_usage
CREATE OR REPLACE FUNCTION public.increment_template_usage(p_template_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  UPDATE reminder_templates
  SET usage_count = usage_count + 1
  WHERE id = p_template_id;
END;
$function$
;

-- MISMATCH: apply_budget_template
CREATE OR REPLACE FUNCTION public.apply_budget_template(p_space_id uuid, p_template_id uuid, p_monthly_income numeric)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_category RECORD;
BEGIN
  -- Verify user has access to the space
  IF NOT EXISTS (
    SELECT 1 FROM space_members 
    WHERE space_id = p_space_id AND user_id = auth.uid()
  ) THEN
    RAISE EXCEPTION 'Access denied to space';
  END IF;

  -- Delete existing budget categories for this space
  DELETE FROM budget_categories WHERE space_id = p_space_id;

  -- Insert new categories based on template
  FOR v_category IN
    SELECT 
      category_name,
      percentage,
      icon,
      color,
      description
    FROM budget_template_categories
    WHERE template_id = p_template_id
    ORDER BY sort_order
  LOOP
    INSERT INTO budget_categories (
      space_id,
      category_name,
      allocated_amount,
      spent_amount,
      icon,
      color
    ) VALUES (
      p_space_id,
      v_category.category_name,
      ROUND((p_monthly_income * v_category.percentage / 100)::numeric, 2),
      0,
      v_category.icon,
      v_category.color
    );
  END LOOP;
END;
$function$
;

-- MISMATCH: calculate_expense_splits
CREATE OR REPLACE FUNCTION public.calculate_expense_splits(p_expense_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  v_expense RECORD;
  v_space_members uuid[];
  v_partner RECORD;
  v_user1_share numeric;
  v_user2_share numeric;
  v_total_income numeric;
BEGIN
  SELECT id, space_id, amount, paid_by, split_type, ownership, is_split,
         split_percentage_user1, split_percentage_user2,
         split_amount_user1, split_amount_user2
  INTO v_expense
  FROM expenses
  WHERE id = p_expense_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Expense not found: %', p_expense_id;
  END IF;

  IF v_expense.is_split IS NOT TRUE THEN
    DELETE FROM expense_splits WHERE expense_id = p_expense_id;
    RETURN;
  END IF;

  SELECT array_agg(user_id ORDER BY joined_at)
  INTO v_space_members
  FROM space_members
  WHERE space_id = v_expense.space_id;

  IF v_space_members IS NULL OR array_length(v_space_members, 1) < 2 THEN
    DELETE FROM expense_splits WHERE expense_id = p_expense_id;
    RETURN;
  END IF;

  DELETE FROM expense_splits WHERE expense_id = p_expense_id;

  CASE COALESCE(v_expense.split_type, 'equal')
    WHEN 'equal' THEN
      v_user1_share := ROUND(v_expense.amount / 2, 2);
      v_user2_share := v_expense.amount - v_user1_share;

    WHEN 'percentage' THEN
      v_user1_share := ROUND(v_expense.amount * COALESCE(v_expense.split_percentage_user1, 50) / 100, 2);
      v_user2_share := v_expense.amount - v_user1_share;

    WHEN 'fixed' THEN
      v_user1_share := COALESCE(v_expense.split_amount_user1, ROUND(v_expense.amount / 2, 2));
      v_user2_share := COALESCE(v_expense.split_amount_user2, v_expense.amount - v_user1_share);

    WHEN 'income-based' THEN
      SELECT user1_id, user2_id, user1_income, user2_income
      INTO v_partner
      FROM partnership_balances
      WHERE space_id = v_expense.space_id
      LIMIT 1;

      IF v_partner IS NULL THEN
        v_user1_share := ROUND(v_expense.amount / 2, 2);
        v_user2_share := v_expense.amount - v_user1_share;
      ELSE
        v_total_income := COALESCE(v_partner.user1_income, 0) + COALESCE(v_partner.user2_income, 0);
        IF v_total_income = 0 THEN
          v_user1_share := ROUND(v_expense.amount / 2, 2);
          v_user2_share := v_expense.amount - v_user1_share;
        ELSE
          IF v_space_members[1] = v_partner.user1_id THEN
            v_user1_share := ROUND(v_expense.amount * COALESCE(v_partner.user1_income, 0) / v_total_income, 2);
          ELSE
            v_user1_share := ROUND(v_expense.amount * COALESCE(v_partner.user2_income, 0) / v_total_income, 2);
          END IF;
          v_user2_share := v_expense.amount - v_user1_share;
        END IF;
      END IF;

    ELSE
      v_user1_share := ROUND(v_expense.amount / 2, 2);
      v_user2_share := v_expense.amount - v_user1_share;
  END CASE;

  IF v_expense.ownership = 'yours' THEN
    v_user1_share := v_expense.amount;
    v_user2_share := 0;
  ELSIF v_expense.ownership = 'theirs' THEN
    v_user1_share := 0;
    v_user2_share := v_expense.amount;
  END IF;

  INSERT INTO expense_splits (expense_id, user_id, amount_owed, percentage, is_payer, status)
  VALUES (
    p_expense_id, v_space_members[1], v_user1_share,
    CASE WHEN v_expense.amount > 0 THEN ROUND(v_user1_share / v_expense.amount * 100, 2) ELSE 0 END,
    (v_expense.paid_by = v_space_members[1]), 'pending'
  );

  INSERT INTO expense_splits (expense_id, user_id, amount_owed, percentage, is_payer, status)
  VALUES (
    p_expense_id, v_space_members[2], v_user2_share,
    CASE WHEN v_expense.amount > 0 THEN ROUND(v_user2_share / v_expense.amount * 100, 2) ELSE 0 END,
    (v_expense.paid_by = v_space_members[2]), 'pending'
  );
END;
$function$
;

-- MISMATCH: create_goal_activity
CREATE OR REPLACE FUNCTION public.create_goal_activity()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
  BEGIN
    -- Create activity feed entry for new goals
    PERFORM create_activity_feed_entry(
      NEW.space_id,
      NEW.created_by,
      'goal_created',
      jsonb_build_object(
        'goal_title', NEW.title,
        'goal_description', NEW.description,
        'priority', NEW.priority,
        'target_date', NEW.target_date
      ),
      NEW.id
    );

    RETURN NEW;
  END;
  $function$
;

-- MISMATCH: create_milestone_activity
CREATE OR REPLACE FUNCTION public.create_milestone_activity()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
  DECLARE
    v_space_id UUID;
    v_goal_title TEXT;
  BEGIN
    -- Only trigger when milestone_reached changes from FALSE to TRUE
    IF NEW.milestone_reached = TRUE AND (OLD IS NULL OR OLD.milestone_reached = FALSE) THEN
      -- Get space_id and goal title
      SELECT g.space_id, g.title INTO v_space_id, v_goal_title
      FROM goals g
      WHERE g.id = NEW.goal_id;

      -- Create activity feed entry
      PERFORM create_activity_feed_entry(
        v_space_id,
        NEW.user_id,
        'milestone_reached',
        jsonb_build_object(
          'goal_title', v_goal_title,
          'check_in_content', NEW.content,
          'progress_rating', NEW.progress_rating
        ),
        NEW.goal_id,
        NEW.id
      );
    END IF;

    RETURN NEW;
  END;
  $function$
;

-- MISMATCH: generate_recurring_instances
CREATE OR REPLACE FUNCTION public.generate_recurring_instances(template_id_param uuid, until_date date)
 RETURNS integer
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  v_template RECORD;
  v_current_date date;
  v_period_end date;
  v_interval_days integer;
  v_days_of_week integer[];
  v_day_of_month integer;
  v_count integer := 0;
  v_dow integer;
  v_last_period_start date;
BEGIN
  SELECT id, space_id, recurrence_type, recurrence_pattern, start_date, end_date,
         target_value, is_active
  INTO v_template
  FROM recurring_goal_templates
  WHERE id = template_id_param;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Template not found: %', template_id_param;
  END IF;

  IF v_template.is_active IS NOT TRUE THEN
    RETURN 0;
  END IF;

  IF v_template.end_date IS NOT NULL AND until_date > v_template.end_date THEN
    until_date := v_template.end_date;
  END IF;

  SELECT MAX(period_start) INTO v_last_period_start
  FROM recurring_goal_instances
  WHERE template_id = template_id_param;

  IF v_last_period_start IS NOT NULL THEN
    v_current_date := v_last_period_start + interval '1 day';
  ELSE
    v_current_date := v_template.start_date;
  END IF;

  v_interval_days := COALESCE((v_template.recurrence_pattern->>'interval')::integer, 1);

  CASE v_template.recurrence_type
    WHEN 'daily' THEN
      WHILE v_current_date <= until_date LOOP
        IF NOT EXISTS (
          SELECT 1 FROM recurring_goal_instances
          WHERE template_id = template_id_param AND period_start = v_current_date
        ) THEN
          INSERT INTO recurring_goal_instances (
            template_id, period_start, period_end, target_value,
            status, auto_generated, generation_date
          ) VALUES (
            template_id_param, v_current_date, v_current_date,
            COALESCE(v_template.target_value, 1), 'pending', true, now()
          );
          v_count := v_count + 1;
        END IF;
        v_current_date := v_current_date + (v_interval_days || ' days')::interval;
      END LOOP;

    WHEN 'weekly' THEN
      IF v_template.recurrence_pattern ? 'days_of_week' THEN
        SELECT array_agg(val::integer)
        INTO v_days_of_week
        FROM jsonb_array_elements_text(v_template.recurrence_pattern->'days_of_week') AS val;
      ELSE
        v_days_of_week := ARRAY[0,1,2,3,4,5,6];
      END IF;

      WHILE v_current_date <= until_date LOOP
        v_dow := EXTRACT(DOW FROM v_current_date)::integer;
        IF v_dow = ANY(v_days_of_week) THEN
          IF NOT EXISTS (
            SELECT 1 FROM recurring_goal_instances
            WHERE template_id = template_id_param AND period_start = v_current_date
          ) THEN
            INSERT INTO recurring_goal_instances (
              template_id, period_start, period_end, target_value,
              status, auto_generated, generation_date
            ) VALUES (
              template_id_param, v_current_date, v_current_date,
              COALESCE(v_template.target_value, 1), 'pending', true, now()
            );
            v_count := v_count + 1;
          END IF;
        END IF;
        v_current_date := v_current_date + interval '1 day';
      END LOOP;

    WHEN 'monthly' THEN
      v_day_of_month := COALESCE((v_template.recurrence_pattern->>'day_of_month')::integer, 1);
      WHILE v_current_date <= until_date LOOP
        v_current_date := make_date(
          EXTRACT(YEAR FROM v_current_date)::integer,
          EXTRACT(MONTH FROM v_current_date)::integer,
          LEAST(v_day_of_month,
            EXTRACT(DAY FROM (date_trunc('month', v_current_date) + interval '1 month - 1 day'))::integer)
        );
        IF v_current_date <= until_date THEN
          v_period_end := (date_trunc('month', v_current_date) + interval '1 month - 1 day')::date;
          IF NOT EXISTS (
            SELECT 1 FROM recurring_goal_instances
            WHERE template_id = template_id_param AND period_start = v_current_date
          ) THEN
            INSERT INTO recurring_goal_instances (
              template_id, period_start, period_end, target_value,
              status, auto_generated, generation_date
            ) VALUES (
              template_id_param, v_current_date, v_period_end,
              COALESCE(v_template.target_value, 1), 'pending', true, now()
            );
            v_count := v_count + 1;
          END IF;
        END IF;
        v_current_date := (date_trunc('month', v_current_date) + interval '1 month')::date;
      END LOOP;

    ELSE
      -- Custom or unknown: fall back to daily with configured interval
      WHILE v_current_date <= until_date LOOP
        IF NOT EXISTS (
          SELECT 1 FROM recurring_goal_instances
          WHERE template_id = template_id_param AND period_start = v_current_date
        ) THEN
          INSERT INTO recurring_goal_instances (
            template_id, period_start, period_end, target_value,
            status, auto_generated, generation_date
          ) VALUES (
            template_id_param, v_current_date, v_current_date,
            COALESCE(v_template.target_value, 1), 'pending', true, now()
          );
          v_count := v_count + 1;
        END IF;
        v_current_date := v_current_date + (v_interval_days || ' days')::interval;
      END LOOP;
  END CASE;

  RETURN v_count;
END;
$function$
;

-- MISMATCH: is_admin
CREATE OR REPLACE FUNCTION public.is_admin(user_id uuid DEFAULT auth.uid())
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
    -- Check if the user exists in admin_users table and is active
    RETURN EXISTS (
        SELECT 1 FROM admin_users
        WHERE admin_users.user_id = is_admin.user_id
        AND is_active = true
    );
END;
$function$
;

-- MISMATCH: generate_secure_share_token
CREATE OR REPLACE FUNCTION public.generate_secure_share_token()
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions', 'pg_temp'
AS $function$
DECLARE
  random_bytes bytea;
  base64_string text;
BEGIN
  -- Explicit `extensions.` qualifier in case search_path resolution
  -- fails for any reason. Both should be safe — pgcrypto is universally
  -- in `extensions` on Supabase, but we add the SET search_path above
  -- as belt-and-suspenders.
  random_bytes := extensions.gen_random_bytes(32);

  base64_string := encode(random_bytes, 'base64');
  base64_string := REPLACE(REPLACE(TRIM(TRAILING '=' FROM base64_string), '+', '-'), '/', '_');

  RETURN base64_string;
END;
$function$
;

-- MISMATCH: handle_new_user_workspace_provisioning
CREATE OR REPLACE FUNCTION public.handle_new_user_workspace_provisioning()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  new_space_id UUID;
  space_name_to_use TEXT;
  pending_invitation RECORD;
BEGIN
  -- Skip if user already has a space membership
  IF EXISTS (SELECT 1 FROM space_members WHERE user_id = NEW.id) THEN
    RETURN NEW;
  END IF;

  -- Check if this user has a pending invitation (invited users don't get a default space)
  SELECT id, space_id, role INTO pending_invitation
  FROM space_invitations
  WHERE email = NEW.email
    AND status = 'pending'
  ORDER BY created_at DESC
  LIMIT 1;

  IF pending_invitation.id IS NOT NULL THEN
    -- User was invited - add them to the inviter's space instead of creating a new space
    INSERT INTO space_members (
      space_id,
      user_id,
      role,
      joined_at
    ) VALUES (
      pending_invitation.space_id,
      NEW.id,
      pending_invitation.role,  -- Use the role from the invitation
      NOW()
    );

    -- Mark the invitation as accepted
    UPDATE space_invitations
    SET status = 'accepted',
        accepted_at = NOW()
    WHERE id = pending_invitation.id;

    RAISE LOG 'Added invited user % to space % with role %', NEW.id, pending_invitation.space_id, pending_invitation.role;
    RETURN NEW;
  END IF;

  -- Not an invited user - create default space as normal
  space_name_to_use := COALESCE(
    (
      SELECT raw_user_meta_data->>'space_name'
      FROM auth.users
      WHERE id = NEW.id
    ),
    NEW.name || '''s Space'
  );

  INSERT INTO spaces (
    name,
    is_personal,
    auto_created,
    user_id,
    created_at,
    updated_at
  ) VALUES (
    space_name_to_use,
    true,
    true,
    NEW.id,
    NOW(),
    NOW()
  )
  RETURNING id INTO new_space_id;

  INSERT INTO space_members (
    space_id,
    user_id,
    role,
    joined_at
  ) VALUES (
    new_space_id,
    NEW.id,
    'owner',
    NOW()
  );

  RAISE LOG 'Auto-provisioned workspace % for user %', new_space_id, NEW.id;

  RETURN NEW;
EXCEPTION
  WHEN OTHERS THEN
    RAISE LOG 'Failed to auto-provision workspace for user %: %', NEW.id, SQLERRM;
    RETURN NEW;
END;
$function$
;

-- MISMATCH: get_user_subscription_tier
CREATE OR REPLACE FUNCTION public.get_user_subscription_tier(p_user_id uuid)
 RETURNS text
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_tier TEXT;
  v_trial_ends_at TIMESTAMPTZ;
BEGIN
  SELECT tier, trial_ends_at INTO v_tier, v_trial_ends_at
  FROM public.subscriptions
  WHERE user_id = p_user_id
    AND status = 'active';

  -- No subscription found = free tier
  IF v_tier IS NULL THEN
    RETURN 'free';
  END IF;

  -- If user has paid tier, return it
  IF v_tier IN ('pro', 'family') THEN
    RETURN v_tier;
  END IF;

  -- If user is in active trial, give them Pro tier access
  IF v_trial_ends_at IS NOT NULL AND v_trial_ends_at > NOW() THEN
    RETURN 'pro';  -- Trial users get Pro features
  END IF;

  -- Default to free tier
  RETURN 'free';
END;
$function$
;

-- MISMATCH: calculate_space_storage
CREATE OR REPLACE FUNCTION public.calculate_space_storage(p_space_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'storage'
AS $function$
DECLARE
  v_total_bytes bigint := 0;
  v_file_count  integer := 0;
  v_limit_bytes bigint;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM spaces WHERE id = p_space_id) THEN
    RAISE EXCEPTION 'Space not found: %', p_space_id;
  END IF;

  SELECT COALESCE(SUM((o.metadata->>'size')::bigint), 0),
         COALESCE(COUNT(*), 0)
  INTO v_total_bytes, v_file_count
  FROM storage.objects o
  INNER JOIN space_members sm ON o.owner::uuid = sm.user_id
  WHERE sm.space_id = p_space_id;

  SELECT storage_limit_bytes INTO v_limit_bytes
  FROM storage_usage WHERE space_id = p_space_id;

  IF v_limit_bytes IS NULL THEN
    v_limit_bytes := 536870912; -- 512 MB default
  END IF;

  INSERT INTO storage_usage (space_id, total_bytes, file_count, storage_limit_bytes, last_calculated_at, updated_at)
  VALUES (p_space_id, v_total_bytes, v_file_count, v_limit_bytes, now(), now())
  ON CONFLICT (space_id)
  DO UPDATE SET
    total_bytes = EXCLUDED.total_bytes,
    file_count = EXCLUDED.file_count,
    last_calculated_at = now(),
    updated_at = now();
END;
$function$
;

-- MISMATCH: delete_oauth_tokens
CREATE OR REPLACE FUNCTION public.delete_oauth_tokens(p_connection_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'vault'
AS $function$
DECLARE
  v_access_key TEXT;
  v_refresh_key TEXT;
BEGIN
  -- Build the vault secret keys
  v_access_key := 'calendar_' || p_connection_id || '_access_token';
  v_refresh_key := 'calendar_' || p_connection_id || '_refresh_token';
  
  -- Delete access token from vault
  DELETE FROM vault.secrets WHERE name = v_access_key;
  
  -- Delete refresh token from vault
  DELETE FROM vault.secrets WHERE name = v_refresh_key;
END;
$function$
;

-- MISMATCH: update_calendar_table_statistics
CREATE OR REPLACE FUNCTION public.update_calendar_table_statistics()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  ANALYZE calendar_connections;
  ANALYZE calendar_event_mappings;
  ANALYZE calendar_sync_logs;
  ANALYZE calendar_sync_conflicts;
  ANALYZE calendar_webhook_subscriptions;
  ANALYZE calendar_sync_queue;

  RAISE NOTICE 'Calendar table statistics updated successfully';
END;
$function$
;

-- MISMATCH: queue_calendar_sync_on_change
CREATE OR REPLACE FUNCTION public.queue_calendar_sync_on_change()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  v_connection RECORD;
  v_operation queue_operation;
  v_priority INTEGER;
  v_event_snapshot JSONB;
BEGIN
  -- Determine operation type
  IF TG_OP = 'DELETE' THEN
    v_operation := 'delete';
    v_event_snapshot := row_to_json(OLD)::JSONB;
  ELSIF TG_OP = 'INSERT' THEN
    v_operation := 'create';
    v_event_snapshot := NULL;
  ELSE
    v_operation := 'update';
    v_event_snapshot := NULL;
  END IF;

  -- Don't queue if event is currently locked for sync (prevents loops)
  IF (TG_OP = 'UPDATE' AND NEW.sync_locked = TRUE) OR
     (TG_OP = 'INSERT' AND NEW.sync_locked = TRUE) THEN
    RETURN COALESCE(NEW, OLD);
  END IF;

  -- Don't queue if this change came from external sync
  IF TG_OP = 'UPDATE' AND NEW.last_external_sync IS NOT NULL AND
     OLD.last_external_sync IS NOT NULL AND
     NEW.last_external_sync > OLD.last_external_sync THEN
    RETURN NEW;
  END IF;

  -- Calculate priority
  IF TG_OP = 'DELETE' THEN
    v_priority := calculate_sync_priority(OLD.id, v_operation);
  ELSE
    v_priority := calculate_sync_priority(NEW.id, v_operation);
  END IF;

  -- Find all active connections for this event's space
  FOR v_connection IN
    SELECT id, provider
    FROM calendar_connections
    WHERE space_id = COALESCE(NEW.space_id, OLD.space_id)
      AND sync_status = 'active'
      AND (sync_direction = 'bidirectional' OR sync_direction = 'outbound_only')
  LOOP
    -- Queue sync operation for this connection
    INSERT INTO calendar_sync_queue (
      event_id,
      connection_id,
      mapping_id,
      operation,
      priority,
      event_snapshot
    ) VALUES (
      COALESCE(NEW.id, OLD.id),
      v_connection.id,
      (SELECT id FROM calendar_event_mappings
       WHERE rowan_event_id = COALESCE(NEW.id, OLD.id)
         AND connection_id = v_connection.id
       LIMIT 1),
      v_operation,
      v_priority,
      v_event_snapshot
    )
    ON CONFLICT DO NOTHING;
  END LOOP;

  RETURN COALESCE(NEW, OLD);
END;
$function$
;

-- MISMATCH: mark_queue_item_failed
CREATE OR REPLACE FUNCTION public.mark_queue_item_failed(p_queue_id uuid, p_error_message text)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  v_retry_count INTEGER;
  v_next_retry TIMESTAMPTZ;
BEGIN
  SELECT retry_count INTO v_retry_count
  FROM calendar_sync_queue
  WHERE id = p_queue_id;

  IF v_retry_count = 0 THEN
    v_next_retry := NOW() + INTERVAL '1 minute';
  ELSIF v_retry_count = 1 THEN
    v_next_retry := NOW() + INTERVAL '5 minutes';
  ELSE
    v_next_retry := NOW() + INTERVAL '15 minutes';
  END IF;

  UPDATE calendar_sync_queue
  SET
    status = 'failed',
    retry_count = retry_count + 1,
    last_error = p_error_message,
    next_retry_at = CASE WHEN retry_count + 1 < max_retries THEN v_next_retry ELSE NULL END,
    updated_at = NOW()
  WHERE id = p_queue_id;
END;
$function$
;

-- MISMATCH: claim_founding_member_number
CREATE OR REPLACE FUNCTION public.claim_founding_member_number()
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  claimed_number INTEGER;
BEGIN
  -- Lock the counter row and increment if under limit
  UPDATE public.founding_member_counter
  SET
    current_count = current_count + 1,
    updated_at = NOW()
  WHERE id = 1 AND current_count < max_count
  RETURNING current_count INTO claimed_number;

  RETURN claimed_number;
END;
$function$
;

-- MISMATCH: record_task_snooze
CREATE OR REPLACE FUNCTION public.record_task_snooze()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NEW.is_snoozed = TRUE AND (OLD.is_snoozed IS NULL OR OLD.is_snoozed = FALSE) THEN
    -- Increment snooze count
    NEW.snooze_count = COALESCE(OLD.snooze_count, 0) + 1;

    -- Record in history
    INSERT INTO task_snooze_history (
      task_id,
      snoozed_by,
      snoozed_from_date,
      snoozed_to_date,
      snooze_duration_minutes
    ) VALUES (
      NEW.id,
      NEW.snoozed_by,
      NEW.due_date,
      CASE
        WHEN NEW.snoozed_until IS NOT NULL
        THEN NEW.snoozed_until::DATE
        ELSE NULL
      END,
      CASE
        WHEN NEW.snoozed_until IS NOT NULL AND NEW.due_date IS NOT NULL
        THEN EXTRACT(EPOCH FROM (NEW.snoozed_until - NEW.due_date::TIMESTAMPTZ)) / 60
        ELSE NULL
      END
    );
  END IF;

  RETURN NEW;
END;
$function$
;

-- MISMATCH: mark_reminder_sent
CREATE OR REPLACE FUNCTION public.mark_reminder_sent(reminder_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  UPDATE task_reminders
  SET
    is_sent = TRUE,
    sent_at = NOW()
  WHERE id = reminder_id;
END;
$function$
;

-- MISMATCH: record_task_handoff
CREATE OR REPLACE FUNCTION public.record_task_handoff()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  current_user_id UUID;
BEGIN
  -- Only record if assigned_to actually changed
  IF NEW.assigned_to IS DISTINCT FROM OLD.assigned_to THEN
    -- Get current user (from session context or use created_by as fallback)
    current_user_id := current_setting('app.current_user_id', TRUE)::UUID;
    IF current_user_id IS NULL THEN
      current_user_id := NEW.created_by;
    END IF;

    -- Record the handoff
    INSERT INTO task_handoffs (
      task_id,
      from_user_id,
      to_user_id,
      performed_by,
      performed_at
    ) VALUES (
      NEW.id,
      OLD.assigned_to,
      NEW.assigned_to,
      current_user_id,
      NOW()
    );
  END IF;

  RETURN NEW;
END;
$function$
;

-- MISMATCH: process_chore_rotations
CREATE OR REPLACE FUNCTION public.process_chore_rotations()
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  rotation_record RECORD;
  next_user_id UUID;
BEGIN
  -- Find rotations due today
  FOR rotation_record IN
    SELECT * FROM chore_rotations
    WHERE is_active = TRUE
      AND next_rotation_date <= CURRENT_DATE
  LOOP
    -- Get next user in rotation
    next_user_id := get_next_rotation_user(rotation_record.id);

    -- Update chore assignment
    UPDATE chores
    SET assigned_to = next_user_id
    WHERE id = rotation_record.chore_id;

    -- Update rotation record
    UPDATE chore_rotations
    SET
      last_rotation_date = CURRENT_DATE,
      last_assigned_to = next_user_id,
      next_rotation_date = CASE rotation_frequency
        WHEN 'daily' THEN CURRENT_DATE + INTERVAL '1 day'
        WHEN 'weekly' THEN CURRENT_DATE + INTERVAL '1 week'
        WHEN 'biweekly' THEN CURRENT_DATE + INTERVAL '2 weeks'
        WHEN 'monthly' THEN CURRENT_DATE + INTERVAL '1 month'
        ELSE CURRENT_DATE + INTERVAL '1 week'
      END
    WHERE id = rotation_record.id;
  END LOOP;
END;
$function$
;

-- MISMATCH: mark_queue_item_processing
CREATE OR REPLACE FUNCTION public.mark_queue_item_processing(p_queue_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  UPDATE calendar_sync_queue
  SET status = 'processing', updated_at = NOW()
  WHERE id = p_queue_id;
END;
$function$
;

-- LOCAL_ONLY drops (24 functions absent from prod)
DROP FUNCTION IF EXISTS public.trigger_calculate_splits CASCADE;
DROP FUNCTION IF EXISTS public.update_partnership_balance_on_settlement CASCADE;
DROP FUNCTION IF EXISTS public.auto_archive_old_tasks CASCADE;
DROP FUNCTION IF EXISTS public.auto_archive_old_events CASCADE;
DROP FUNCTION IF EXISTS public.log_compliance_event CASCADE;
DROP FUNCTION IF EXISTS public.initialize_user_privacy_preferences CASCADE;
DROP FUNCTION IF EXISTS public.update_goal_progress_from_checkin CASCADE;
DROP FUNCTION IF EXISTS public.create_checkin_activity CASCADE;
DROP FUNCTION IF EXISTS public.update_comment_reaction_counts CASCADE;
DROP FUNCTION IF EXISTS public.create_checkin_reaction_activity CASCADE;
DROP FUNCTION IF EXISTS public.calculate_next_checkin_date CASCADE;
DROP FUNCTION IF EXISTS public.schedule_next_checkin_reminder CASCADE;
DROP FUNCTION IF EXISTS public.trigger_schedule_checkin_reminders CASCADE;
DROP FUNCTION IF EXISTS public.mark_checkin_reminder_completed CASCADE;
DROP FUNCTION IF EXISTS public.create_voice_transcription_entry CASCADE;
DROP FUNCTION IF EXISTS public.search_voice_transcriptions CASCADE;
DROP FUNCTION IF EXISTS public.calculate_next_occurrence CASCADE;
DROP FUNCTION IF EXISTS public.update_habit_streaks CASCADE;
DROP FUNCTION IF EXISTS public.auto_generate_habit_instances CASCADE;
DROP FUNCTION IF EXISTS public.update_chore_calendar_events_updated_at CASCADE;
DROP FUNCTION IF EXISTS public.sync_chore_to_calendar CASCADE;
DROP FUNCTION IF EXISTS public.update_calendar_event_from_chore CASCADE;
DROP FUNCTION IF EXISTS public.verify_calendar_rls_enabled CASCADE;
DROP FUNCTION IF EXISTS public.check_calendar_index_health CASCADE;

DO $$
BEGIN
  RAISE NOTICE '✅ Phase 9.3: snapped migrations source-of-truth to prod state';
END
$$;
