-- =============================================================================
-- Migration: Phase 9.3 — close remaining 9 MISMATCHes (post-regex-fix)
-- Date: 2026-05-08
--
-- WHY:
-- PR #395 (Phase 9.3 path B) closed 25 MISMATCH + 24 LOCAL_ONLY drift
-- items via auto-generated CREATE OR REPLACE / DROP IF EXISTS. After
-- merge, the post-deploy verification revealed 9 NEW MISMATCHes the
-- inventory hadn't seen — they were hidden by a regex bug in
-- scripts/database/inventory-drift-extended.ts that required `AS` to
-- appear BEFORE `LANGUAGE` in CREATE FUNCTION blocks. Functions whose
-- migration source used the `LANGUAGE ... AS` ordering (which is what
-- pg_get_functiondef emits) silently categorized as "match" even when
-- bodies differed.
--
-- Inventory script fix shipped alongside this migration in the same PR.
--
-- The 9 functions surfaced (all real prod-side body divergences):
--   • sync_task_to_calendar
--   • can_access_user_profile
--   • initialize_subscription
--   • check_storage_quota
--   • handle_token_expiry
--   • update_token_expiry
--   • record_feature_event
--   • get_founding_member_spots_remaining
--   • get_dashboard_summary
--
-- Same path-B treatment: CREATE OR REPLACE FUNCTION with prod's body
-- (extracted via pg_get_functiondef on 2026-05-08). Auto-generated by
-- scripts/database/snap-to-prod-generator.ts.
--
-- POST-DEPLOY VERIFY:
--   `npx tsx scripts/database/inventory-drift-extended.ts` → expect
--   MISMATCH: 0, LOCAL_ONLY: 0.
-- =============================================================================


-- MISMATCH: sync_task_to_calendar
CREATE OR REPLACE FUNCTION public.sync_task_to_calendar()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  user_wants_sync BOOLEAN;
  new_event_id UUID;
BEGIN
  -- Only sync if task has a due_date
  IF NEW.due_date IS NULL THEN
    RETURN NEW;
  END IF;

  -- Check if user wants tasks on calendar (default TRUE)
  SELECT COALESCE(show_tasks_on_calendar, TRUE)
  INTO user_wants_sync
  FROM users
  WHERE id = NEW.created_by;

  IF user_wants_sync THEN
    -- Create calendar event
    INSERT INTO events (
      space_id,
      title,
      description,
      event_type,
      start_time,
      end_time,
      assigned_to,
      created_by
    ) VALUES (
      NEW.space_id,
      '📋 ' || NEW.title, -- Prefix with task emoji
      COALESCE(NEW.description, 'Task from Tasks page'),
      'task',
      NEW.due_date::TIMESTAMPTZ,
      (NEW.due_date::TIMESTAMPTZ + INTERVAL '1 hour'), -- Default 1-hour duration
      NEW.assigned_to,
      NEW.created_by
    )
    RETURNING id INTO new_event_id;

    -- Create sync record
    INSERT INTO task_calendar_events (task_id, event_id, is_synced, sync_enabled)
    VALUES (NEW.id, new_event_id, TRUE, TRUE);
  END IF;

  RETURN NEW;
END;
$function$
;


-- MISMATCH: can_access_user_profile
CREATE OR REPLACE FUNCTION public.can_access_user_profile(target_user_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
BEGIN
  -- Fast path: always allow access to own profile
  IF auth.uid() = target_user_id THEN
    RETURN TRUE;
  END IF;

  -- Admin path: use the non-recursive admin check
  IF public.check_is_admin() THEN
    RETURN TRUE;
  END IF;

  -- Secondary path: check if users share any spaces
  RETURN EXISTS (
    SELECT 1
    FROM public.space_members sm1
    JOIN public.space_members sm2 ON sm1.space_id = sm2.space_id
    WHERE sm1.user_id = auth.uid()
      AND sm2.user_id = target_user_id
  );
END;
$function$
;


-- MISMATCH: initialize_subscription
CREATE OR REPLACE FUNCTION public.initialize_subscription(p_user_id uuid)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_subscription_id UUID;
BEGIN
  -- Create subscription with 14-day trial (full Pro features during trial)
  INSERT INTO public.subscriptions (
    user_id,
    tier,
    status,
    period,
    subscription_started_at,
    trial_started_at,
    trial_ends_at
  )
  VALUES (
    p_user_id,
    'free',          -- Base tier is free (trial gives Pro access)
    'active',
    'monthly',
    NOW(),
    NOW(),           -- Trial starts now
    NOW() + INTERVAL '14 days'  -- Trial ends in 14 days
  )
  ON CONFLICT (user_id) DO NOTHING -- Skip if already exists
  RETURNING id INTO v_subscription_id;

  RETURN v_subscription_id;
END;
$function$
;


-- MISMATCH: check_storage_quota
CREATE OR REPLACE FUNCTION public.check_storage_quota(p_space_id uuid, p_file_size_bytes bigint)
 RETURNS TABLE(allowed boolean, current_bytes bigint, limit_bytes bigint, available_bytes bigint, percentage_used numeric)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_current_bytes bigint;
  v_limit_bytes   bigint;
  v_available     bigint;
  v_pct_used      numeric;
BEGIN
  SELECT su.total_bytes, su.storage_limit_bytes
  INTO v_current_bytes, v_limit_bytes
  FROM storage_usage su
  WHERE su.space_id = p_space_id;

  IF NOT FOUND THEN
    PERFORM calculate_space_storage(p_space_id);
    SELECT su.total_bytes, su.storage_limit_bytes
    INTO v_current_bytes, v_limit_bytes
    FROM storage_usage su
    WHERE su.space_id = p_space_id;
    IF NOT FOUND THEN
      v_current_bytes := 0;
      v_limit_bytes := 536870912;
    END IF;
  END IF;

  v_available := GREATEST(v_limit_bytes - v_current_bytes, 0);
  v_pct_used := CASE
    WHEN v_limit_bytes > 0 THEN ROUND((v_current_bytes::numeric / v_limit_bytes) * 100, 2)
    ELSE 0
  END;

  RETURN QUERY SELECT
    (p_file_size_bytes <= v_available),
    v_current_bytes,
    v_limit_bytes,
    v_available,
    v_pct_used;
END;
$function$
;


-- MISMATCH: handle_token_expiry
CREATE OR REPLACE FUNCTION public.handle_token_expiry(p_connection_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  UPDATE calendar_connections
  SET 
    sync_status = 'token_expired',
    updated_at = NOW()
  WHERE id = p_connection_id;
END;
$function$
;


-- MISMATCH: update_token_expiry
CREATE OR REPLACE FUNCTION public.update_token_expiry(p_connection_id uuid, p_expires_in_seconds integer)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  UPDATE calendar_connections
  SET 
    token_expires_at = NOW() + (p_expires_in_seconds || ' seconds')::INTERVAL,
    updated_at = NOW()
  WHERE id = p_connection_id;
END;
$function$
;


-- MISMATCH: record_feature_event
CREATE OR REPLACE FUNCTION public.record_feature_event(p_user_id uuid, p_space_id uuid, p_feature text, p_action text, p_metadata jsonb DEFAULT '{}'::jsonb, p_device_type text DEFAULT NULL::text, p_browser text DEFAULT NULL::text, p_os text DEFAULT NULL::text, p_session_id text DEFAULT NULL::text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  new_id UUID;
BEGIN
  INSERT INTO feature_events (
    user_id,
    space_id,
    feature,
    action,
    metadata,
    device_type,
    browser,
    os,
    session_id
  ) VALUES (
    p_user_id,
    p_space_id,
    p_feature,
    p_action,
    p_metadata,
    p_device_type,
    p_browser,
    p_os,
    p_session_id
  )
  RETURNING id INTO new_id;

  RETURN new_id;
END;
$function$
;


-- MISMATCH: get_founding_member_spots_remaining
CREATE OR REPLACE FUNCTION public.get_founding_member_spots_remaining()
 RETURNS integer
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT max_count - current_count FROM public.founding_member_counter WHERE id = 1;
$function$
;


-- MISMATCH: get_dashboard_summary
CREATE OR REPLACE FUNCTION public.get_dashboard_summary(p_space_id uuid, p_user_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
    v_result JSONB := '{}'::JSONB;
    v_today DATE := CURRENT_DATE;
    v_now TIMESTAMPTZ := CURRENT_TIMESTAMP;
    v_week_start TIMESTAMPTZ := date_trunc('week', CURRENT_TIMESTAMP);
    v_month_start TIMESTAMPTZ := date_trunc('month', CURRENT_TIMESTAMP);
BEGIN
    -- Verify user has access
    IF NOT EXISTS (SELECT 1 FROM space_members WHERE space_id = p_space_id AND user_id = p_user_id) THEN
        RAISE EXCEPTION 'User does not have access to this space';
    END IF;

    v_result := jsonb_build_object(
        -- TASKS
        'tasks', (
            SELECT jsonb_build_object(
                'total', COUNT(*),
                'pending', COUNT(*) FILTER (WHERE status = 'pending'),
                'inProgress', COUNT(*) FILTER (WHERE status = 'in_progress'),
                'completed', COUNT(*) FILTER (WHERE status = 'completed'),
                'dueToday', COUNT(*) FILTER (WHERE due_date::date = v_today AND status != 'completed'),
                'overdue', COUNT(*) FILTER (WHERE due_date::date < v_today AND status NOT IN ('completed', 'cancelled')),
                'highPriority', COUNT(*) FILTER (WHERE priority IN ('high', 'urgent') AND status != 'completed'),
                'assignedToMe', COUNT(*) FILTER (WHERE assigned_to = p_user_id AND status != 'completed'),
                'trend', 0
            )
            FROM tasks WHERE space_id = p_space_id
        ),
        'recentTasks', COALESCE((
            SELECT jsonb_agg(row_to_json(t))
            FROM (
                SELECT id, title, status, priority, due_date, assigned_to
                FROM tasks
                WHERE space_id = p_space_id AND status != 'completed'
                ORDER BY
                    CASE priority WHEN 'urgent' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,
                    due_date ASC NULLS LAST
                LIMIT 5
            ) t
        ), '[]'::JSONB),

        -- CHORES (due_date, not next_due_date)
        'chores', (
            SELECT jsonb_build_object(
                'total', COUNT(*),
                'pending', COUNT(*) FILTER (WHERE status = 'pending'),
                'dueToday', COUNT(*) FILTER (WHERE due_date::date = v_today AND status != 'completed'),
                'overdue', COUNT(*) FILTER (WHERE due_date::date < v_today AND status NOT IN ('completed', 'cancelled')),
                'assignedToMe', COUNT(*) FILTER (WHERE assigned_to = p_user_id AND status != 'completed'),
                'assignedToPartner', COUNT(*) FILTER (WHERE assigned_to IS NOT NULL AND assigned_to != p_user_id AND status != 'completed'),
                'completedThisWeek', COUNT(*) FILTER (WHERE status = 'completed' AND completed_at >= v_week_start),
                'trend', 0
            )
            FROM chores WHERE space_id = p_space_id
        ),
        'recentChores', '[]'::JSONB,

        -- CALENDAR EVENTS (no is_shared column)
        'events', (
            SELECT jsonb_build_object(
                'total', COUNT(*),
                'today', COUNT(*) FILTER (WHERE start_time::date = v_today),
                'thisWeek', COUNT(*) FILTER (WHERE start_time >= v_week_start AND start_time < v_week_start + INTERVAL '7 days'),
                'upcoming', COUNT(*) FILTER (WHERE start_time >= v_now),
                'personal', 0,
                'shared', 0,
                'trend', 0
            )
            FROM calendar_events WHERE space_id = p_space_id
        ),
        'nextEvent', (
            SELECT row_to_json(e)
            FROM (
                SELECT id, title, start_time, end_time, location, all_day
                FROM calendar_events
                WHERE space_id = p_space_id AND start_time >= v_now
                ORDER BY start_time ASC
                LIMIT 1
            ) e
        ),

        -- REMINDERS (reminder_time, not remind_at for time-based queries)
        'reminders', (
            SELECT jsonb_build_object(
                'total', COUNT(*),
                'active', COUNT(*) FILTER (WHERE status IN ('active', 'pending')),
                'completed', COUNT(*) FILTER (WHERE status = 'completed' OR completed = true),
                'overdue', COUNT(*) FILTER (WHERE reminder_time < v_now AND status NOT IN ('completed', 'dismissed') AND completed = false),
                'dueToday', COUNT(*) FILTER (WHERE reminder_time::date = v_today AND status NOT IN ('completed', 'dismissed') AND completed = false),
                'trend', 0
            )
            FROM reminders WHERE space_id = p_space_id
        ),
        'nextReminder', (
            SELECT row_to_json(r)
            FROM (
                SELECT id, title, reminder_time, priority
                FROM reminders
                WHERE space_id = p_space_id AND reminder_time >= v_now AND status NOT IN ('completed', 'dismissed') AND completed = false
                ORDER BY reminder_time ASC
                LIMIT 1
            ) r
        ),

        -- MESSAGES
        'messages', (
            SELECT jsonb_build_object(
                'total', COUNT(*),
                'today', COUNT(*) FILTER (WHERE created_at::date = v_today),
                'trend', 0
            )
            FROM messages WHERE space_id = p_space_id
        ),
        'messageStats', jsonb_build_object('unread', 0, 'conversations', 0),
        'lastMessage', NULL,

        -- SHOPPING LISTS
        'shopping', (
            SELECT jsonb_build_object(
                'totalLists', COUNT(*),
                'activeLists', COUNT(*) FILTER (WHERE status = 'active' OR completed_at IS NULL),
                'urgentList', NULL::TEXT
            )
            FROM shopping_lists WHERE space_id = p_space_id
        ),
        -- SHOPPING ITEMS (checked column exists in DB)
        'shoppingItems', (
            SELECT jsonb_build_object(
                'totalItems', COUNT(*),
                'checkedToday', COUNT(*) FILTER (WHERE si.checked = true AND si.updated_at::date = v_today),
                'uncheckedItems', COUNT(*) FILTER (WHERE si.checked = false),
                'checkedThisWeek', COUNT(*) FILTER (WHERE si.checked = true AND si.updated_at >= v_week_start)
            )
            FROM shopping_items si
            INNER JOIN shopping_lists sl ON si.list_id = sl.id
            WHERE sl.space_id = p_space_id
        ),

        -- MEALS
        'meals', (
            SELECT jsonb_build_object(
                'thisWeek', COUNT(*) FILTER (WHERE scheduled_date >= v_week_start AND scheduled_date < v_week_start + INTERVAL '7 days'),
                'mealsToday', COUNT(*) FILTER (WHERE scheduled_date::date = v_today),
                'trend', 0
            )
            FROM meals WHERE space_id = p_space_id
        ),
        'savedRecipes', (SELECT COUNT(*) FROM recipes WHERE space_id = p_space_id),
        'nextMeal', (
            SELECT row_to_json(m)
            FROM (
                SELECT id, COALESCE(name, meal_type) as recipe_name, meal_type, scheduled_date
                FROM meals
                WHERE space_id = p_space_id AND scheduled_date::date >= v_today
                ORDER BY scheduled_date ASC
                LIMIT 1
            ) m
        ),

        -- BUDGET (allocated_amount, not monthly_budget)
        'budget', (
            SELECT jsonb_build_object(
                'monthlyBudget', COALESCE(SUM(allocated_amount), 0),
                'pendingBills', 0
            )
            FROM budget_categories WHERE space_id = p_space_id
        ),
        'expenses', (
            SELECT jsonb_build_object(
                'spentThisMonth', COALESCE(SUM(amount), 0)
            )
            FROM expenses WHERE space_id = p_space_id AND created_at >= v_month_start
        ),

        -- PROJECTS (budget_amount, not budget)
        'projects', (
            SELECT jsonb_build_object(
                'total', COUNT(*),
                'planning', COUNT(*) FILTER (WHERE status = 'planning'),
                'inProgress', COUNT(*) FILTER (WHERE status = 'in_progress'),
                'completed', COUNT(*) FILTER (WHERE status = 'completed'),
                'onHold', COUNT(*) FILTER (WHERE status = 'on_hold'),
                'totalBudget', COALESCE(SUM(budget_amount), 0),
                'totalExpenses', COALESCE(SUM(actual_cost), 0),
                'trend', 0
            )
            FROM projects WHERE space_id = p_space_id
        ),

        -- GOALS
        'goals', (
            SELECT jsonb_build_object(
                'total', COUNT(*),
                'active', COUNT(*) FILTER (WHERE status IN ('active', 'in_progress')),
                'completed', COUNT(*) FILTER (WHERE status = 'completed'),
                'overallProgress', COALESCE(AVG(progress) FILTER (WHERE status IN ('active', 'in_progress')), 0)::INTEGER,
                'trend', 0
            )
            FROM goals WHERE space_id = p_space_id
        ),
        'topGoal', (
            SELECT row_to_json(g)
            FROM (
                SELECT id, title, progress, target_date
                FROM goals
                WHERE space_id = p_space_id AND status IN ('active', 'in_progress')
                ORDER BY progress DESC
                LIMIT 1
            ) g
        )
    );

    RETURN v_result;
END;
$function$
;


DO $$
BEGIN
  RAISE NOTICE '✅ Phase 9.3 hotfix: closed 9 final MISMATCHes (regex bug surfaced)';
END
$$;
